name: Build the develop version using Spack

# This workflow is disabled because Bedrock hasn't been adapted to
# the develop version of current Mochi packages

on:
  workflow_dispatch: {}
#  schedule:
#  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build the main version of the package
    steps:
    - uses: actions/checkout@v4
    - uses: mochi-hpc/mochi-test-build-action@v1
      with:
        package-name: hepnos
        package-version: "@develop"
